### ISSUE TITLE
Insecure requests to tumblr API

### ISSUE THREAD

**Issue by herdivineshadow** [fabacab/tumblr-crosspostr#31]
Tumblr no longer support [insecure requests to their API](https://engineering.tumblr.com/post/665757792757563392/https-required-on-tumblr-api) - would appreciate instructions on what I need to do to my install of tumblr-crosspostr to make it work again please.

**Comment by fabacab** [comment]
I don't support this plugin at all anymore but this might be as simple as adding an `s` to the `http:` URL on [this line of code](https://github.com/fabacab/tumblr-crosspostr/blob/master/lib/OAuthWP_Tumblr.php#L8).
